server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080 #指定sentinel 控制台服务的地址
        port: 8719
      eager: true #取消懒加载，服务启动即可在sentinel 控制台中看到
      filter:
        url-patterns: /**

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ribbon:
  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒
logging:
  level:
    com.atguigu.guli.service.edu.feign.OssFileService: debug #以什么级别监控哪个接口
# 开启feign 对sentinel 的支持
feign:
  sentinel:
    enabled: true
