server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyId: LTAI4G1w6fep9osSRpPDUKhk #你的keyid
    keySecret: 2sM5g0U3T64Rt4wpUAlj94gP9EbIu8 #你的keysecret
    templateGroupId: b569050cb01653c065a08e9f5ad42a42 #你配置的转码模板组id 加密模板
    workflowId: 0dad7eb15d229d8db9b84b3591b00c67 #你配置的工作流id 不审核不加密转码上传